### ISSUE TITLE
Base bounds on v2.0.0

### ISSUE THREAD

**Issue by thumphries** [tov/preprocessor-tools-hs#1]
Hello,

v2.0.0 on Hackage has a rather permissive `base` bound, this causes build failures when using any `base` without `Data.Semigroup`.

e.g. using GHC 8.0.2 I see 

```
cabal: Entering directory '/home/ubuntu/.mafia/packages/2/x86_64-unknown-linux/8.0.2/preprocessor-tools-2.0.0-70c8fbf2be721613afceef192da4bbf2562d2e6b/src/preprocessor-tools-2.0.0'
Configuring preprocessor-tools-2.0.0...
Building preprocessor-tools-2.0.0...
Preprocessing library preprocessor-tools-2.0.0...
[ 1 of 10] Compiling Language.Haskell.Preprocessor.SynSpec ( Language/Haskell/Preprocessor/SynSpec.hs, dist/dist-sandbox-7275f190/build/Language/Haskell/Preprocessor/SynSpec.o )

Language/Haskell/Preprocessor/SynSpec.hs:16:10: error:
    Not in scope: type constructor or class ‘Semigroup’
```

Any chance of a revision on that specific version?

**Comment by tov** [comment]
Oh, sorry about that. I'll set a bound for `base` and release as 2.0.1.

**Comment by thumphries** [comment]
2.0.1 and 2.0.2 exist and both look correct to me - you should be able to edit the package metadata for 2.0.0 via the Hackage web interface and add a base >= 4.11 constraint.

Sorry for the hassle!

**Comment by tov** [comment]
I'm sorry for the trouble—I've edited the base bound for 2.0.0.

**Comment by tov** [comment]
(I didn't know I could. Thanks!)

**Comment by thumphries** [comment]
Thanks so much, all resolved :)
